import React, { useState } from "react";
import { type AuthUser } from "wasp/auth";
import { getAttendanceCommandCenter, useQuery } from "wasp/client/operations";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Badge, M3Card, M3CircularProgress, M3TextField } from "../../client/components/m3";

export function AttendanceCommandCenterPage({ user }: { user: AuthUser }) {
  const [dateOnly,setDateOnly]=useState(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()));
  const q=useQuery(getAttendanceCommandCenter,{dateOnly}); const d:any=q.data;
  const stats=d?[{l:"Hadir",v:d.hadir},{l:"Terlambat",v:d.terlambat},{l:"Sakit",v:d.sakit},{l:"Izin",v:d.izin},{l:"Alpa",v:d.alpa},{l:"Perlu verifikasi",v:d.needsReview}]:[];
  return <SchoolLayout user={user}><div className="space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.08em] text-md-primary">Attendance 360</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.02em]">Command Center Kehadiran</h1><p className="mt-1 text-sm text-md-on-surface-variant">Monitoring kehadiran sekolah berbasis rekap resmi dan evidence event.</p></div><M3TextField type="date" label="Tanggal" value={dateOnly} onChange={e=>setDateOnly(e.target.value)}/></header>
  {q.isLoading?<div className="flex min-h-[260px] items-center justify-center"><M3CircularProgress size={36}/></div>:d&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{stats.map(s=><M3Card key={s.l} variant="outlined" className="p-4"><p className="text-[11px] text-md-on-surface-variant">{s.l}</p><p className="mt-1 text-2xl font-semibold">{s.v}</p></M3Card>)}</div>
  <M3Card variant="outlined" className="p-4"><div className="flex flex-wrap gap-2 text-xs"><M3Badge variant="outline">Total siswa {d.totalStudents}</M3Badge><M3Badge variant="outline">Rekap {d.recordedCount}</M3Badge><M3Badge variant="primary">Check-in {d.checkedIn}</M3Badge><M3Badge variant="outline">Check-out {d.checkedOut}</M3Badge><M3Badge variant="warning">Pulang awal {d.earlyLeave}</M3Badge></div></M3Card>
  <div className="grid gap-4 lg:grid-cols-2"><M3Card variant="outlined" className="p-4"><h2 className="font-semibold">Per Tingkat</h2><div className="mt-3 space-y-2">{d.byGrade.map((r:any)=><div key={r.key} className="flex items-center justify-between rounded-[10px] bg-md-surface-container px-3 py-2 text-xs"><span>{r.label} · {r.recordedCount}/{r.studentCount}</span><strong>{r.rate==null?"—":`${r.rate}%`}</strong></div>)}</div></M3Card><M3Card variant="outlined" className="p-4"><h2 className="font-semibold">Per Jurusan / Konsentrasi</h2><div className="mt-3 space-y-2">{d.byDepartment.map((r:any)=><div key={r.key} className="flex items-center justify-between rounded-[10px] bg-md-surface-container px-3 py-2 text-xs"><span>{r.label} · {r.recordedCount}/{r.studentCount}</span><strong>{r.rate==null?"—":`${r.rate}%`}</strong></div>)}</div></M3Card></div>
  <div className="grid gap-4 lg:grid-cols-2"><M3Card variant="outlined" className="p-4"><h2 className="font-semibold">Per Tingkat</h2><div className="mt-3 space-y-2">{d.byGrade.map((r:any)=><div key={r.key} className="flex items-center justify-between rounded-[10px] bg-md-surface-container px-3 py-2 text-xs"><span className="font-semibold">{r.label}</span><span>{r.recordedCount}/{r.studentCount} tercatat · {r.rate==null?"—":`${r.rate}%`}</span></div>)}</div></M3Card><M3Card variant="outlined" className="p-4"><h2 className="font-semibold">Per Program / Jurusan</h2><div className="mt-3 space-y-2">{d.byDepartment.map((r:any)=><div key={r.key} className="flex items-center justify-between rounded-[10px] bg-md-surface-container px-3 py-2 text-xs"><span className="font-semibold">{r.label}</span><span>{r.recordedCount}/{r.studentCount} tercatat · {r.rate==null?"—":`${r.rate}%`}</span></div>)}</div></M3Card></div>
  <M3Card variant="outlined" className="overflow-hidden"><div className="border-b border-md-outline-variant/35 p-4"><h2 className="font-semibold">Rombel Hari Ini</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-md-surface-container"><tr><th className="px-4 py-3">Rombel</th><th>Rekap</th><th>H</th><th>T</th><th>S</th><th>I</th><th>A</th><th>Review</th><th>%</th></tr></thead><tbody>{d.byClass.map((r:any)=><tr key={r.id} className="border-t border-md-outline-variant/25"><td className="px-4 py-3 font-semibold">{r.name}</td><td>{r.recordedCount}/{r.studentCount}</td><td>{r.hadir}</td><td>{r.terlambat}</td><td>{r.sakit}</td><td>{r.izin}</td><td>{r.alpa}</td><td>{r.needsReview}</td><td>{r.rate==null?"—":`${r.rate}%`}</td></tr>)}</tbody></table></div></M3Card></>}
  </div></SchoolLayout>;
}
