import React, { useEffect, useState } from "react";
import { type AuthUser } from "wasp/auth";
import { deleteAttendanceCalendarDay, getAttendanceSettings, saveAttendanceCalendarDay, saveAttendancePolicy, useQuery } from "wasp/client/operations";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Badge, M3Banner, M3Button, M3Card, M3CircularProgress, M3Dialog, M3Select, M3TextField } from "../../client/components/m3";
import { formatCoordinatePair, mapsUrl, parseCoordinatePair, parseCoordinateValue, validateSchoolCoordinates } from "../coordinates";

const types=["SCHOOL_DAY","HOLIDAY","NATIONAL_HOLIDAY","SEMESTER_BREAK","SCHOOL_EVENT","EXAM_DAY","SPECIAL_SCHEDULE"].map(value=>({value,label:value.replaceAll("_"," ")}));
export function AttendanceSettingsPage({ user }: { user: AuthUser }) {
  const q=useQuery(getAttendanceSettings); const d:any=q.data;
  const [form,setForm]=useState<any>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [open,setOpen]=useState(false); const [day,setDay]=useState<any>({dateOnly:"",type:"HOLIDAY",label:"",notes:"",checkInOpenOverride:"",lateAfterOverride:"",checkInCloseOverride:"",checkOutOpenOverride:"",checkOutCloseOverride:""});
  useEffect(()=>{if(d?.policy)setForm({...d.policy,latitude:d.policy.latitude??"",longitude:d.policy.longitude??""});},[d?.policy]);
  const geo=validateSchoolCoordinates(String(form?.latitude??""),String(form?.longitude??""));
  const setBoth=(pair:{latitude:number;longitude:number})=>{setForm((f:any)=>({...f,latitude:String(pair.latitude),longitude:String(pair.longitude)}));setError("");};
  const geoField=(field:"latitude"|"longitude",label:string,hint?:string)=>(
    <M3TextField label={label} type="text" inputMode="decimal" autoComplete="off" spellCheck={false} value={String(form[field])} supportingText={geo[field]?undefined:hint} error={geo[field]??undefined}
      onPaste={(e)=>{const pair=parseCoordinatePair(e.clipboardData.getData("text"));if(pair){e.preventDefault();setBoth(pair);}}}
      onChange={(e)=>{const pair=parseCoordinatePair(e.target.value);if(pair){setBoth(pair);return;}const value=e.target.value;setForm((f:any)=>({...f,[field]:value}));}}/>
  );
  const save=async()=>{
    if(!form)return;
    setError("");setMessage("");
    const latText=String(form.latitude).trim(),lngText=String(form.longitude).trim();
    const hasCoords=latText!==""&&lngText!=="";
    const invalid=geo.latitude||geo.longitude;
    if(invalid){setError(invalid);return;}
    if(form.isActive&&!hasCoords){setError("Kebijakan aktif membutuhkan koordinat sekolah. Isi latitude dan longitude, atau nonaktifkan kebijakan terlebih dahulu.");return;}
    const latitude=hasCoords?parseCoordinateValue(latText):null,longitude=hasCoords?parseCoordinateValue(lngText):null;
    setBusy(true);
    try{
      const saved:any=await saveAttendancePolicy({...form,latitude,longitude,radiusMeters:Number(form.radiusMeters),maxGpsAccuracyMeters:Number(form.maxGpsAccuracyMeters)});
      await q.refetch();
      if(hasCoords&&(saved?.latitude!==latitude||saved?.longitude!==longitude)){setError(`Server menyimpan lokasi yang berbeda dari yang dikirim (${formatCoordinatePair(saved?.latitude,saved?.longitude)}). Muat ulang halaman lalu periksa kembali.`);}
      else setMessage(hasCoords?`Kebijakan kehadiran tersimpan. Lokasi sekolah: ${formatCoordinatePair(saved?.latitude,saved?.longitude)}.`:"Kebijakan kehadiran tersimpan. Koordinat sekolah masih kosong.");
    }catch(e:any){setError(e?.message||"Belum tersimpan. Periksa isian lalu coba lagi.");}
    finally{setBusy(false);}
  };
  const savedPolicy=d?.policy;const hasSavedLoc=savedPolicy?.latitude!=null&&savedPolicy?.longitude!=null;
  const savedAt=savedPolicy?.updatedAt?`${new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",dateStyle:"medium",timeStyle:"short"}).format(new Date(savedPolicy.updatedAt))} WIB`:null;
  const saveDay=async()=>{setBusy(true);try{await saveAttendanceCalendarDay({...day,notes:day.notes||null,checkInOpenOverride:day.checkInOpenOverride||null,lateAfterOverride:day.lateAfterOverride||null,checkInCloseOverride:day.checkInCloseOverride||null,checkOutOpenOverride:day.checkOutOpenOverride||null,checkOutCloseOverride:day.checkOutCloseOverride||null});setOpen(false);await q.refetch();}catch(e:any){alert(e?.message||"Kalender belum tersimpan.");}finally{setBusy(false);}};
  return <SchoolLayout user={user}><div className="space-y-5"><header><p className="text-[11px] font-semibold uppercase tracking-[.08em] text-md-primary">Attendance 360</p><h1 className="mt-1 text-2xl font-semibold">Pengaturan Kehadiran</h1><p className="mt-1 text-sm text-md-on-surface-variant">Geofence, jam operasional, akurasi GPS, selfie dan kalender sekolah.</p></header>{message&&<M3Banner variant="success" supportingText={message} dismissible onDismiss={()=>setMessage("")}/>}{error&&<M3Banner variant="error" supportingText={error} dismissible onDismiss={()=>setError("")}/>} {q.isLoading||!form?<div className="flex min-h-[220px] items-center justify-center"><M3CircularProgress size={34}/></div>:<>
  <div data-testid="saved-location" className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[12.5px] text-md-on-surface-variant"><span>Lokasi tersimpan di server: <strong className="text-md-on-surface">{hasSavedLoc?formatCoordinatePair(savedPolicy.latitude,savedPolicy.longitude):"belum diatur"}</strong></span><span>{savedAt?`Terakhir diubah ${savedAt}`:"Kebijakan belum pernah disimpan"}</span>{hasSavedLoc&&<a href={mapsUrl(savedPolicy.latitude,savedPolicy.longitude)} target="_blank" rel="noopener noreferrer" className="font-semibold text-md-primary hover:underline">Lihat di peta</a>}</div><M3Card variant="outlined" className="p-5 space-y-4"><div className="grid gap-3 md:grid-cols-2">{geoField("latitude","Latitude sekolah","Boleh tempel pasangan \"lat, lng\" dari peta; otomatis dipisah.")}{geoField("longitude","Longitude sekolah")}<M3TextField label="Radius geofence (m)" type="number" value={String(form.radiusMeters)} onChange={e=>setForm({...form,radiusMeters:e.target.value})}/><M3TextField label="Akurasi GPS maksimum (m)" type="number" value={String(form.maxGpsAccuracyMeters)} onChange={e=>setForm({...form,maxGpsAccuracyMeters:e.target.value})}/><M3TextField label="Check-in dibuka" value={form.checkInOpen} onChange={e=>setForm({...form,checkInOpen:e.target.value})}/><M3TextField label="Terlambat setelah" value={form.lateAfter} onChange={e=>setForm({...form,lateAfter:e.target.value})}/><M3TextField label="Check-in ditutup" value={form.checkInClose} onChange={e=>setForm({...form,checkInClose:e.target.value})}/><M3TextField label="Check-out dibuka" value={form.checkOutOpen} onChange={e=>setForm({...form,checkOutOpen:e.target.value})}/><M3TextField label="Check-out ditutup" value={form.checkOutClose} onChange={e=>setForm({...form,checkOutClose:e.target.value})}/><M3TextField label="Hari kerja (0=Minggu…6=Sabtu)" value={form.workingDays} onChange={e=>setForm({...form,workingDays:e.target.value})}/></div><div className="flex flex-wrap gap-3 text-xs"><label><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Aktif</label><label><input type="checkbox" checked={form.allowStudentCheckIn} onChange={e=>setForm({...form,allowStudentCheckIn:e.target.checked})}/> Check-in siswa</label><label><input type="checkbox" checked={form.allowStudentCheckOut} onChange={e=>setForm({...form,allowStudentCheckOut:e.target.checked})}/> Check-out siswa</label><label><input type="checkbox" checked={form.requireCheckInSelfie} onChange={e=>setForm({...form,requireCheckInSelfie:e.target.checked})}/> Selfie masuk wajib</label><label><input type="checkbox" checked={form.requireCheckOutSelfie} onChange={e=>setForm({...form,requireCheckOutSelfie:e.target.checked})}/> Selfie pulang wajib</label></div><M3Button onClick={save} isLoading={busy}>Simpan Kebijakan</M3Button></M3Card>
  <M3Card variant="outlined" className="overflow-hidden"><div className="flex items-center justify-between border-b border-md-outline-variant/35 p-4"><div><h2 className="font-semibold">Kalender Operasional</h2><p className="text-[11px] text-md-on-surface-variant">Override libur, ujian, event, atau jadwal khusus.</p></div><M3Button size="sm" icon="add" onClick={()=>{setDay({dateOnly:"",type:"HOLIDAY",label:"",notes:"",checkInOpenOverride:"",lateAfterOverride:"",checkInCloseOverride:"",checkOutOpenOverride:"",checkOutCloseOverride:""});setOpen(true);}}>Tambah</M3Button></div><div className="divide-y divide-md-outline-variant/25">{d.calendarDays.map((r:any)=><div key={r.id} className="flex items-center gap-3 p-4"><div className="flex-1"><p className="text-sm font-semibold">{r.dateOnly} · {r.label}</p><p className="text-[11px] text-md-on-surface-variant">{r.type}{r.notes?` · ${r.notes}`:""}</p></div><M3Badge variant="outline" size="sm">{r.type}</M3Badge><M3Button variant="text" size="sm" onClick={()=>{setDay({...r,checkInOpenOverride:r.checkInOpenOverride||"",lateAfterOverride:r.lateAfterOverride||"",checkInCloseOverride:r.checkInCloseOverride||"",checkOutOpenOverride:r.checkOutOpenOverride||"",checkOutCloseOverride:r.checkOutCloseOverride||""});setOpen(true);}}>Edit</M3Button><M3Button variant="text" size="sm" onClick={async()=>{if(confirm("Hapus tanggal kalender ini?")){await deleteAttendanceCalendarDay({id:r.id});await q.refetch();}}}>Hapus</M3Button></div>)}{!d.calendarDays.length&&<p className="p-5 text-sm text-md-on-surface-variant">Belum ada tanggal khusus.</p>}</div></M3Card></>}
  <M3Dialog isOpen={open} onClose={()=>setOpen(false)} title="Kalender Kehadiran" actions={<><M3Button variant="text" onClick={()=>setOpen(false)}>Batal</M3Button><M3Button onClick={saveDay} isLoading={busy}>Simpan</M3Button></>}><div className="space-y-3"><M3TextField type="date" label="Tanggal" value={day.dateOnly} onChange={e=>setDay({...day,dateOnly:e.target.value})}/><M3Select label="Tipe" value={day.type} onChange={e=>setDay({...day,type:e.target.value})} options={types}/><M3TextField label="Label" value={day.label} onChange={e=>setDay({...day,label:e.target.value})}/><M3TextField label="Catatan" value={day.notes} onChange={e=>setDay({...day,notes:e.target.value})}/><div className="grid gap-2 sm:grid-cols-2"><M3TextField label="Override check-in buka" value={day.checkInOpenOverride} onChange={e=>setDay({...day,checkInOpenOverride:e.target.value})}/><M3TextField label="Override batas terlambat" value={day.lateAfterOverride} onChange={e=>setDay({...day,lateAfterOverride:e.target.value})}/><M3TextField label="Override check-in tutup" value={day.checkInCloseOverride} onChange={e=>setDay({...day,checkInCloseOverride:e.target.value})}/><M3TextField label="Override check-out buka" value={day.checkOutOpenOverride} onChange={e=>setDay({...day,checkOutOpenOverride:e.target.value})}/><M3TextField label="Override check-out tutup" value={day.checkOutCloseOverride} onChange={e=>setDay({...day,checkOutCloseOverride:e.target.value})}/></div></div></M3Dialog>
  </div></SchoolLayout>;
}
