import React, { useEffect, useMemo, useState } from "react";
import { type AuthUser } from "wasp/auth";
import { closeAttendanceActivity, createAttendanceActivity, getAttendanceActivities, recordAttendanceActivity, useQuery } from "wasp/client/operations";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Badge, M3Button, M3Card, M3CircularProgress, M3Dialog, M3Select, M3TextField } from "../../client/components/m3";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export function HabituationAttendancePage({user}:{user:AuthUser}){
  const [dateOnly,setDateOnly]=useState(today());const q=useQuery(getAttendanceActivities,{dateOnly});const d:any=q.data;
  const [activityOpen,setActivityOpen]=useState(false);const [form,setForm]=useState({code:"",name:"",category:"PEMBIASAAN",startTime:"06:30",endTime:"07:00",notes:""});
  const [selectedId,setSelectedId]=useState("");const [classId,setClassId]=useState("");const [draft,setDraft]=useState<Record<string,{status:string;notes:string}>>({});const [busy,setBusy]=useState(false);
  const activities:any[]=d?.activities||[];const classes:any[]=d?.classes||[];const selected=activities.find(a=>a.id===selectedId)||activities[0]||null;const selectedClass=classes.find(c=>c.id===classId)||classes[0]||null;
  useEffect(()=>{if(selected&&!selectedId)setSelectedId(selected.id);},[selected?.id]);useEffect(()=>{if(selectedClass&&!classId)setClassId(selectedClass.id);},[selectedClass?.id]);
  useEffect(()=>{if(!selected||!selectedClass)return;const existing=new Map((selected.records||[]).map((r:any)=>[r.studentId,r]));setDraft(Object.fromEntries(selectedClass.students.map((s:any)=>{const e:any=existing.get(s.id);return[s.id,{status:e?.status||"HADIR",notes:e?.notes||""}]})));},[selected?.id,selectedClass?.id]);
  const create=async()=>{setBusy(true);try{await createAttendanceActivity({dateOnly,code:form.code,name:form.name,category:form.category,startTime:form.startTime||null,endTime:form.endTime||null,notes:form.notes||null});setActivityOpen(false);setForm({code:"",name:"",category:"PEMBIASAAN",startTime:"06:30",endTime:"07:00",notes:""});await q.refetch();}catch(e:any){alert(e?.message||"Kegiatan belum tersimpan.");}finally{setBusy(false);}};
  const save=async()=>{if(!selected||!selectedClass)return;setBusy(true);try{await recordAttendanceActivity({activityId:selected.id,records:selectedClass.students.map((s:any)=>({studentId:s.id,status:draft[s.id]?.status||"HADIR",notes:draft[s.id]?.notes||null}))});await q.refetch();}catch(e:any){alert(e?.message||"Presensi pembiasaan belum tersimpan.");}finally{setBusy(false);}};
  const summary=useMemo(()=>selectedClass?selectedClass.students.reduce((a:any,s:any)=>{const st=draft[s.id]?.status||"HADIR";a[st]=(a[st]||0)+1;return a;},{}):{},[draft,selectedClass]);
  return <SchoolLayout user={user}><div className="space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.08em] text-md-primary">Attendance 360</p><h1 className="mt-1 text-2xl font-semibold">Pembiasaan & Kegiatan Karakter</h1><p className="mt-1 text-sm text-md-on-surface-variant">Partisipasi kegiatan dicatat terpisah dari status hadir sekolah.</p></div><div className="flex gap-2"><M3TextField type="date" label="Tanggal" value={dateOnly} onChange={e=>setDateOnly(e.target.value)}/><M3Button icon="add" onClick={()=>setActivityOpen(true)}>Kegiatan</M3Button></div></header>{q.isLoading?<div className="flex min-h-[240px] items-center justify-center"><M3CircularProgress size={34}/></div>:<>
  <M3Card variant="outlined" className="p-4"><div className="grid gap-3 md:grid-cols-2"><M3Select label="Kegiatan" value={selected?.id||""} onChange={e=>setSelectedId(e.target.value)} options={activities.map(a=>({value:a.id,label:`${a.name} · ${a.status}`}))}/><M3Select label="Rombel" value={selectedClass?.id||""} onChange={e=>setClassId(e.target.value)} options={classes.map(c=>({value:c.id,label:c.name}))}/></div>{selected&&<div className="mt-3 flex flex-wrap items-center gap-2"><M3Badge variant={selected.status==="OPEN"?"success":"outline"}>{selected.status}</M3Badge><span className="text-xs text-md-on-surface-variant">{selected.startTime||"-"}–{selected.endTime||"-"} · tercatat {selected._count?.records||0}</span>{selected.status!=="CLOSED"&&<M3Button variant="text" size="sm" onClick={async()=>{await closeAttendanceActivity({id:selected.id});await q.refetch();}}>Tutup Kegiatan</M3Button>}</div>}</M3Card>
  {selected&&selectedClass?<M3Card variant="outlined" className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-md-outline-variant/35 p-4"><div><h2 className="font-semibold">{selected.name} · {selectedClass.name}</h2><p className="text-[11px] text-md-on-surface-variant">Hadir {summary.HADIR||0} · Tidak hadir {summary.TIDAK_HADIR||0} · Terlambat {summary.TERLAMBAT||0} · Dispensasi {summary.DISPENSASI||0}</p></div><M3Button onClick={save} isLoading={busy} disabled={selected.status==="CLOSED"}>Simpan Presensi</M3Button></div><div className="divide-y divide-md-outline-variant/25">{selectedClass.students.map((s:any)=><div key={s.id} className="grid gap-2 p-3 md:grid-cols-[1fr_190px_1fr]"><div><p className="text-sm font-semibold">{s.name}</p><p className="text-[10.5px] text-md-on-surface-variant">{s.studentProfile?.nis||"-"}</p></div><M3Select value={draft[s.id]?.status||"HADIR"} onChange={e=>setDraft(v=>({...v,[s.id]:{...v[s.id],status:e.target.value}}))} options={["HADIR","TIDAK_HADIR","TERLAMBAT","DISPENSASI"].map(v=>({value:v,label:v.replaceAll("_"," ")}))}/><M3TextField placeholder="Catatan opsional" value={draft[s.id]?.notes||""} onChange={e=>setDraft(v=>({...v,[s.id]:{...v[s.id],notes:e.target.value}}))}/></div>)}</div></M3Card>:<M3Card variant="outlined" className="p-6 text-sm text-md-on-surface-variant">Buat kegiatan lalu pilih rombel untuk mulai mencatat.</M3Card>}</>}
  <M3Dialog isOpen={activityOpen} onClose={()=>setActivityOpen(false)} title="Kegiatan Pembiasaan" actions={<><M3Button variant="text" onClick={()=>setActivityOpen(false)}>Batal</M3Button><M3Button onClick={create} isLoading={busy}>Simpan</M3Button></>}><div className="space-y-3"><M3TextField label="Kode" placeholder="LITERASI" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><M3TextField label="Nama kegiatan" placeholder="Literasi Pagi" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><M3TextField label="Kategori" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><div className="grid grid-cols-2 gap-2"><M3TextField label="Mulai" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/><M3TextField label="Selesai" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></div><M3TextField label="Catatan" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></M3Dialog>
  </div></SchoolLayout>;
}
