import { type AuthUser } from "wasp/auth";
import { createAdministrationDraft, getAdministrationWorkspace, useQuery } from "wasp/client/operations";
import { useNavigate } from "react-router";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Banner, M3Button, M3Card, M3CircularProgress, M3EmptyState, M3Select, M3TextField } from "../../client/components/m3";
import { useMemo, useState } from "react";
import { AdministrationPersonAutocomplete } from "../AdministrationPersonAutocomplete";

const textareaClass="w-full resize-y rounded-[10px] border border-md-outline-variant bg-md-surface px-3.5 py-3 text-[13px] leading-6 text-md-on-surface outline-none focus:border-md-primary focus:ring-2 focus:ring-md-primary/15";
export function AdministrationCreateDraftPage({user}:{user:AuthUser}){
 const workspace=useQuery(getAdministrationWorkspace);const nav=useNavigate();const data:any=workspace.data;
 const [templateId,setTemplateId]=useState("");const [student,setStudent]=useState<any>(null);const [staff,setStaff]=useState<any>(null);const [documentNumber,setDocumentNumber]=useState("");const [recipientName,setRecipientName]=useState("");const [recipientAddress,setRecipientAddress]=useState("");const [subject,setSubject]=useState("");const [notes,setNotes]=useState("");const [manual,setManual]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const activeTemplates=useMemo(()=>(data?.templates||[]).filter((t:any)=>t.status==="ACTIVE"),[data]);const selected=activeTemplates.find((t:any)=>t.id===(templateId||activeTemplates[0]?.id));const version=selected?.versions?.[0];const fields:any[]=version?.variableSchema?.fields||[];
 const submit=async()=>{if(!selected)return;if(!documentNumber.trim()){setError("Nomor surat wajib diisi secara manual.");return;}setBusy(true);setError("");try{const doc:any=await createAdministrationDraft({templateId:selected.id,relatedStudentId:student?.id||null,relatedStaffId:staff?.id||null,documentNumber:documentNumber.trim(),subject:subject||null,recipientName:recipientName||null,recipientAddress:recipientAddress||null,manualData:manual,notes:notes||null});nav(`/school/administration/documents/${doc.id}`)}catch(e:any){setError(e?.message||"Draft belum berhasil dibuat.")}finally{setBusy(false)}};
 if(workspace.isLoading)return <SchoolLayout user={user}><div className="flex min-h-[55vh] items-center justify-center"><M3CircularProgress size={38}/></div></SchoolLayout>;
 return <SchoolLayout user={user}><div className="mx-auto max-w-5xl space-y-5"><header><p className="v2-eyebrow">TATA USAHA</p><h1 className="mt-1 text-2xl font-semibold">Buat Draft Surat</h1><p className="mt-1 text-sm text-md-on-surface-variant">Nomor surat diisi manual. Data siswa, guru/tendik, sekolah, dan Kepala Sekolah diambil langsung dari database School OS.</p></header>
 {workspace.error?<M3Banner variant="error" supportingText={(workspace.error as any)?.message||"Data gagal dimuat."}/>:!data?.initialized?<M3EmptyState icon="description" title="Template belum tersedia" description="Inisialisasi kerangka TU terlebih dahulu." actionLabel="Buka Dashboard TU" actionHref="/school/administration"/>:<><M3Banner variant="warning" supportingText="Mode Starter tetap aktif: nomor dapat dicantumkan manual untuk draft, tetapi status penerbitan resmi/TTE belum diaktifkan."/>{error&&<M3Banner variant="error" supportingText={error} dismissible onDismiss={()=>setError("")}/>}<div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]">
 <M3Card variant="outlined" className="p-4"><div className="space-y-4"><M3Select label="Template" value={selected?.id||""} onChange={e=>{setTemplateId(e.target.value);setManual({});setSubject("")}} options={activeTemplates.map((t:any)=>({label:`${t.name} · ${t.category}`,value:t.id}))}/><M3TextField label="Nomor Surat *" value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)} placeholder="Masukkan nomor sesuai register sekolah" supportingText="Nomor tidak dibuat otomatis pada fase ini; operator TU mengisi manual."/>
 <div className="grid gap-4 md:grid-cols-2"><AdministrationPersonAutocomplete type="STUDENT" label="Siswa terkait (opsional)" placeholder="Cari nama, NIS, NISN, atau rombel" value={student} onChange={setStudent}/><AdministrationPersonAutocomplete type="STAFF" label="Guru / Tendik terkait (opsional)" placeholder="Cari nama, NIP, NUPTK, jabatan, atau unit" value={staff} onChange={setStaff}/></div>
 <M3TextField label="Penerima / tujuan" value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Contoh: Yth. Kepala ..."/><div><label className="mb-1.5 block text-[13px] font-semibold">Alamat penerima (opsional)</label><textarea rows={3} className={textareaClass} value={recipientAddress} onChange={e=>setRecipientAddress(e.target.value)}/></div><M3TextField label="Perihal override (opsional)" value={subject} onChange={e=>setSubject(e.target.value)} supportingText={`Jika kosong, sistem memakai: ${version?.subjectTemplate||selected?.name||"template"}`}/>{fields.map((f:any)=><div key={f.key}>{f.type==="textarea"?<><label className="mb-1.5 block text-[13px] font-semibold">{f.label}{f.required?" *":""}</label><textarea rows={4} className={textareaClass} value={manual[f.key]||""} onChange={e=>setManual({...manual,[f.key]:e.target.value})} placeholder={f.placeholder||""}/></>:<M3TextField type={f.type==="date"?"date":"text"} label={`${f.label}${f.required?" *":""}`} value={manual[f.key]||""} onChange={e=>setManual({...manual,[f.key]:e.target.value})} placeholder={f.placeholder||""}/>}</div>)}<div><label className="mb-1.5 block text-[13px] font-semibold">Catatan internal (opsional)</label><textarea rows={3} className={textareaClass} value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="flex gap-2"><M3Button onClick={submit} isLoading={busy} icon="preview">Buat & Preview Draft</M3Button><M3Button href="/school/administration/outgoing" variant="text">Batal</M3Button></div></div></M3Card>
 <div className="space-y-4"><M3Card variant="filled" className="p-4"><p className="text-xs font-semibold">Template dipilih</p><p className="mt-1 text-base font-semibold">{selected?.name||"-"}</p><p className="mt-1 text-xs leading-5 text-md-on-surface-variant">{selected?.description||""}</p><p className="mt-3 text-[11px] font-medium text-md-primary">Versi {selected?.currentVersion||"-"}</p></M3Card><M3Card variant="outlined" className="p-4"><p className="text-xs font-semibold">Penandatangan default</p>{data.principal?<><p className="mt-2 text-[13px] font-semibold">{data.principal.name}</p><p className="mt-0.5 text-[11px] text-md-on-surface-variant">{data.principal.title}{data.principal.nip?` · NIP ${data.principal.nip}`:""}</p><p className="mt-2 text-[10.5px] leading-4 text-md-on-surface-variant">Diambil otomatis dari assignment Kepala Sekolah pada identitas/struktur sekolah.</p></>:<M3Banner variant="warning" supportingText="Kepala Sekolah belum terkonfigurasi pada struktur sekolah."/>}</M3Card><M3Card variant="outlined" className="p-4"><p className="text-xs font-semibold">Variable otomatis</p><p className="mt-2 text-[11px] leading-5 text-md-on-surface-variant">Siswa dan guru/tendik dipilih melalui pencarian database. Template dapat memakai placeholder student.*, staff.*, principal.*, school.*, dan academicYear.* sesuai whitelist.</p></M3Card></div>
 </div></>}
 </div></SchoolLayout>
}
