import { type AuthUser } from "wasp/auth";
import { getAdministrationWorkspace, initializeAdministrationModule, saveAdministrationTemplate, setAdministrationTemplateStatus, useQuery } from "wasp/client/operations";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Badge, M3Banner, M3Button, M3Card, M3CircularProgress, M3EmptyState, M3TextField } from "../../client/components/m3";
import { useEffect, useMemo, useState } from "react";

const textareaClass="w-full resize-y rounded-[10px] border border-md-outline-variant bg-md-surface px-3.5 py-3 text-[13px] leading-6 text-md-on-surface outline-none focus:border-md-primary focus:ring-2 focus:ring-md-primary/15";
const safePreviewHtml=(input:string)=>{const allowed=new Set(["p","br","strong","b","em","i","u","ul","ol","li","h1","h2","h3","h4","blockquote","table","thead","tbody","tr","th","td","div","span"]);return input.replace(/<!--[\s\S]*?-->/g,"").replace(/<(script|style|iframe|object|embed|form|input|button)[^>]*>[\s\S]*?<\/\1>/gi,"").replace(/<(script|style|iframe|object|embed|form|input|button)[^>]*\/?\s*>/gi,"").replace(/<\/?([a-z0-9]+)(?:\s[^>]*)?>/gi,(match,tag:string)=>{const normalized=tag.toLowerCase();if(!allowed.has(normalized))return"";return match.startsWith("</")?`</${normalized}>`:normalized==="br"?"<br>":`<${normalized}>`;});};
export function AdministrationTemplatesPage({user}:{user:AuthUser}){
 const q=useQuery(getAdministrationWorkspace);const data:any=q.data;const [selectedId,setSelectedId]=useState("");const [form,setForm]=useState<any>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const selected=useMemo(()=>data?.templates?.find((t:any)=>t.id===selectedId)||data?.templates?.[0]||null,[data,selectedId]);
 useEffect(()=>{if(!selected)return;const v=selected.versions?.[0];setSelectedId(selected.id);setForm({name:selected.name,category:selected.category,description:selected.description||"",subjectTemplate:v?.subjectTemplate||"",bodyHtml:v?.bodyHtml||"",variableSchema:v?.variableSchema||{fields:[]}})},[selected?.id,selected?.currentVersion]);
 const init=async()=>{setBusy(true);try{await initializeAdministrationModule({});await q.refetch();}catch(e:any){setMessage(e?.message||"Inisialisasi gagal.")}finally{setBusy(false)}};
 const save=async()=>{if(!selected||!form)return;setBusy(true);setMessage("");try{await saveAdministrationTemplate({id:selected.id,...form});setMessage("Versi baru template berhasil disimpan.");await q.refetch();}catch(e:any){setMessage(e?.message||"Template belum berhasil disimpan.")}finally{setBusy(false)}};
 const toggle=async()=>{if(!selected)return;setBusy(true);try{await setAdministrationTemplateStatus({id:selected.id,status:selected.status==="ACTIVE"?"ARCHIVED":"ACTIVE"});await q.refetch();}catch(e:any){setMessage(e?.message||"Status template belum berubah.")}finally{setBusy(false)}};
 return <SchoolLayout user={user}><div className="space-y-5"><header><p className="v2-eyebrow">TATA USAHA</p><h1 className="mt-1 text-2xl font-semibold">Template Surat</h1><p className="mt-1 text-sm text-md-on-surface-variant">Template starter dapat disesuaikan. Setiap penyimpanan membuat versi baru agar draft lama tetap dapat dilacak.</p></header>
 {q.isLoading?<div className="flex min-h-[45vh] items-center justify-center"><M3CircularProgress size={36}/></div>:q.error?<M3Banner variant="error" supportingText={(q.error as any)?.message||"Data gagal dimuat."}/>:!data?.initialized?<M3Card variant="outlined" className="p-6"><M3EmptyState icon="library_books" title="Template starter belum tersedia" description="Siapkan 10 template umum sebagai kerangka awal." actionLabel="Siapkan Template Starter" onAction={init}/></M3Card>:<>
  <M3Banner variant="warning" supportingText="Template bawaan adalah kerangka umum, bukan format legal final. Sesuaikan kop, redaksi, nomor, approval, dan penandatangan sebelum penerbitan resmi diaktifkan."/>
  {message&&<M3Banner variant={message.includes("berhasil")?"success":"warning"} supportingText={message} dismissible onDismiss={()=>setMessage("")}/>} 
  <div className="grid gap-4 lg:grid-cols-[310px_minmax(0,1fr)]">
   <M3Card variant="outlined" className="overflow-hidden"><div className="border-b border-md-outline-variant px-4 py-3"><h2 className="text-sm font-semibold">Library</h2><p className="text-[11px] text-md-on-surface-variant">{data.templates.length} template</p></div><div className="max-h-[72vh] divide-y divide-md-outline-variant/60 overflow-auto">{data.templates.map((t:any)=><button key={t.id} type="button" onClick={()=>setSelectedId(t.id)} className={`w-full px-4 py-3 text-left transition-colors ${selected?.id===t.id?"bg-md-primary-container/45":"hover:bg-md-surface-container/55"}`}><div className="flex items-start gap-2"><span className="min-w-0 flex-1"><strong className="block truncate text-[12.5px]">{t.name}</strong><span className="mt-0.5 block text-[10.5px] text-md-on-surface-variant">{t.category} · v{t.currentVersion}</span></span><M3Badge variant={t.status==="ACTIVE"?"success":"outline"} size="sm">{t.status}</M3Badge></div></button>)}</div></M3Card>
   {selected&&form&&<div className="space-y-4"><M3Card variant="outlined" className="p-4"><div className="grid gap-3 sm:grid-cols-2"><M3TextField label="Nama template" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><M3TextField label="Kategori" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><div className="sm:col-span-2"><M3TextField label="Deskripsi" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="sm:col-span-2"><M3TextField label="Template perihal" value={form.subjectTemplate} onChange={e=>setForm({...form,subjectTemplate:e.target.value})} supportingText="Boleh memakai placeholder yang diizinkan."/></div><div className="sm:col-span-2"><label className="mb-1.5 block text-[13px] font-semibold">Isi template (HTML terbatas)</label><textarea rows={15} className={textareaClass} value={form.bodyHtml} onChange={e=>setForm({...form,bodyHtml:e.target.value})}/><p className="mt-1 text-[11px] text-md-on-surface-variant">Tag aman: p, br, strong, em, list, heading, blockquote, dan tabel. Script/iframe/form/atribut HTML akan dibuang server.</p></div></div><div className="mt-4 flex flex-wrap gap-2"><M3Button onClick={save} isLoading={busy} icon="save">Simpan sebagai Versi {selected.currentVersion+1}</M3Button><M3Button variant="outlined" onClick={toggle} disabled={busy}>{selected.status==="ACTIVE"?"Arsipkan":"Aktifkan kembali"}</M3Button></div></M3Card>
   <M3Card variant="outlined" className="overflow-hidden"><div className="border-b border-md-outline-variant px-4 py-3"><h2 className="text-sm font-semibold">Preview struktur</h2><p className="text-[11px] text-md-on-surface-variant">Placeholder masih ditampilkan sampai draft dibuat.</p></div><div className="mx-auto my-4 min-h-[500px] max-w-[720px] bg-white p-8 text-[13px] leading-6 text-black shadow-sm"><h3 className="mb-5 text-center text-base font-bold">{form.subjectTemplate||form.name}</h3><div className="[&_table]:w-full [&_td]:align-top [&_td]:py-0.5" dangerouslySetInnerHTML={{__html:safePreviewHtml(form.bodyHtml)}}/></div></M3Card>
   <M3Card variant="filled" className="p-4"><p className="text-xs font-semibold">Field manual template</p><div className="mt-2 flex flex-wrap gap-1.5">{(form.variableSchema?.fields||[]).length?(form.variableSchema.fields||[]).map((f:any)=><M3Badge key={f.key} variant="outline" size="sm">{f.label} · {f.key}</M3Badge>):<span className="text-xs text-md-on-surface-variant">Tidak ada field manual.</span>}</div></M3Card></div>}
  </div></>}
 </div></SchoolLayout>
}
