import { type AuthUser } from "wasp/auth";
import { createAdministrationDraft, getAdministrationStudentOptions, getAdministrationWorkspace, useQuery } from "wasp/client/operations";
import { useNavigate } from "react-router";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Banner, M3Button, M3Card, M3CircularProgress, M3EmptyState, M3Select, M3TextField } from "../../client/components/m3";
import { useMemo, useState } from "react";

const textareaClass="w-full resize-y rounded-[10px] border border-md-outline-variant bg-md-surface px-3.5 py-3 text-[13px] leading-6 text-md-on-surface outline-none focus:border-md-primary focus:ring-2 focus:ring-md-primary/15";
export function AdministrationCreateDraftPage({user}:{user:AuthUser}){
 const workspace=useQuery(getAdministrationWorkspace);const students=useQuery(getAdministrationStudentOptions);const nav=useNavigate();const data:any=workspace.data;const [templateId,setTemplateId]=useState("");const [studentId,setStudentId]=useState("");const [studentSearch,setStudentSearch]=useState("");const [recipientName,setRecipientName]=useState("");const [recipientAddress,setRecipientAddress]=useState("");const [subject,setSubject]=useState("");const [notes,setNotes]=useState("");const [manual,setManual]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const activeTemplates=useMemo(()=>(data?.templates||[]).filter((t:any)=>t.status==="ACTIVE"),[data]);const selected=activeTemplates.find((t:any)=>t.id===(templateId||activeTemplates[0]?.id));const version=selected?.versions?.[0];const fields:any[]=version?.variableSchema?.fields||[];
 const filteredStudents=useMemo(()=>{const q=studentSearch.trim().toLowerCase();return (students.data as any[]||[]).filter(s=>!q||`${s.name||""} ${s.studentProfile?.nis||""} ${s.studentProfile?.nisn||""} ${s.classRoom?.name||""}`.toLowerCase().includes(q)).slice(0,200)},[students.data,studentSearch]);
 const submit=async()=>{if(!selected)return;setBusy(true);setError("");try{const doc:any=await createAdministrationDraft({templateId:selected.id,relatedStudentId:studentId||null,subject:subject||null,recipientName:recipientName||null,recipientAddress:recipientAddress||null,manualData:manual,notes:notes||null});nav(`/school/administration/documents/${doc.id}`)}catch(e:any){setError(e?.message||"Draft belum berhasil dibuat.")}finally{setBusy(false)}};
 if(workspace.isLoading)return <SchoolLayout user={user}><div className="flex min-h-[55vh] items-center justify-center"><M3CircularProgress size={38}/></div></SchoolLayout>;
 return <SchoolLayout user={user}><div className="mx-auto max-w-5xl space-y-5"><header><p className="v2-eyebrow">TATA USAHA</p><h1 className="mt-1 text-2xl font-semibold">Buat Draft Surat</h1><p className="mt-1 text-sm text-md-on-surface-variant">Pilih template umum, isi data yang diperlukan, lalu review hasil render. Belum ada nomor atau tanda tangan resmi.</p></header>
 {workspace.error?<M3Banner variant="error" supportingText={(workspace.error as any)?.message||"Data gagal dimuat."}/>:!data?.initialized?<M3EmptyState icon="description" title="Template belum tersedia" description="Inisialisasi kerangka TU terlebih dahulu." actionLabel="Buka Dashboard TU" actionHref="/school/administration"/>:<><M3Banner variant="warning" supportingText={data.starterMode.message}/>{error&&<M3Banner variant="error" supportingText={error} dismissible onDismiss={()=>setError("")}/>}<div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]">
 <M3Card variant="outlined" className="p-4"><div className="space-y-4"><M3Select label="Template" value={selected?.id||""} onChange={e=>{setTemplateId(e.target.value);setManual({});setSubject("")}} options={activeTemplates.map((t:any)=>({label:`${t.name} · ${t.category}`,value:t.id}))}/><div><M3TextField label="Cari siswa (opsional)" value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} placeholder="Nama, NIS, NISN, atau rombel"/><div className="mt-2"><M3Select label="Subjek siswa" value={studentId} onChange={e=>setStudentId(e.target.value)} options={[{label:"Tidak menggunakan data siswa",value:""},...filteredStudents.map((s:any)=>({label:`${s.name||s.username||"Siswa"} · ${s.classRoom?.name||"Tanpa rombel"} · ${s.studentProfile?.nisn||s.studentProfile?.nis||"-"}`,value:s.id}))]} supportingText={studentSearch&&filteredStudents.length===200?"Hasil dibatasi 200; perjelas pencarian bila perlu.":undefined}/></div></div><M3TextField label="Penerima / tujuan" value={recipientName} onChange={e=>setRecipientName(e.target.value)} placeholder="Contoh: Yth. Kepala ..."/><div><label className="mb-1.5 block text-[13px] font-semibold">Alamat penerima (opsional)</label><textarea rows={3} className={textareaClass} value={recipientAddress} onChange={e=>setRecipientAddress(e.target.value)}/></div><M3TextField label="Perihal override (opsional)" value={subject} onChange={e=>setSubject(e.target.value)} supportingText={`Jika kosong, sistem memakai: ${version?.subjectTemplate||selected?.name||"template"}`}/>{fields.map((f:any)=><div key={f.key}>{f.type==="textarea"?<><label className="mb-1.5 block text-[13px] font-semibold">{f.label}{f.required?" *":""}</label><textarea rows={4} className={textareaClass} value={manual[f.key]||""} onChange={e=>setManual({...manual,[f.key]:e.target.value})} placeholder={f.placeholder||""}/></>:<M3TextField type={f.type==="date"?"date":"text"} label={`${f.label}${f.required?" *":""}`} value={manual[f.key]||""} onChange={e=>setManual({...manual,[f.key]:e.target.value})} placeholder={f.placeholder||""}/>}</div>)}<div><label className="mb-1.5 block text-[13px] font-semibold">Catatan internal (opsional)</label><textarea rows={3} className={textareaClass} value={notes} onChange={e=>setNotes(e.target.value)}/></div><div className="flex gap-2"><M3Button onClick={submit} isLoading={busy} icon="preview">Buat & Preview Draft</M3Button><M3Button href="/school/administration/outgoing" variant="text">Batal</M3Button></div></div></M3Card>
 <div className="space-y-4"><M3Card variant="filled" className="p-4"><p className="text-xs font-semibold">Template dipilih</p><p className="mt-1 text-base font-semibold">{selected?.name||"-"}</p><p className="mt-1 text-xs leading-5 text-md-on-surface-variant">{selected?.description||""}</p><p className="mt-3 text-[11px] font-medium text-md-primary">Versi {selected?.currentVersion||"-"}</p></M3Card><M3Card variant="outlined" className="p-4"><p className="text-xs font-semibold">Variable otomatis</p><p className="mt-2 text-[11px] leading-5 text-md-on-surface-variant">Identitas sekolah selalu diambil dari School OS. Jika siswa dipilih, nama/NIS/NISN/rombel/program/tahun ajaran juga diisi otomatis.</p></M3Card></div>
 </div></>}
 </div></SchoolLayout>
}
