import { type AuthUser } from "wasp/auth";
import { getAdministrationDocument, updateAdministrationDocumentStatus, useQuery } from "wasp/client/operations";
import { useParams } from "react-router";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Badge, M3Banner, M3Button, M3Card, M3CircularProgress } from "../../client/components/m3";
import { useState } from "react";

function variant(status:string){if(status==="APPROVED")return"success" as const;if(status==="IN_REVIEW")return"primary" as const;if(status==="RETURNED_FOR_REVISION")return"warning" as const;if(status==="VOID")return"error" as const;return"outline" as const;}
function fmt(value:any){return new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}
export function AdministrationDocumentPage({user}:{user:AuthUser}){
 const {id=""}=useParams();const q=useQuery(getAdministrationDocument,{id});const data:any=q.data;const doc=data?.document;const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const change=async(status:"DRAFT"|"IN_REVIEW"|"RETURNED_FOR_REVISION"|"APPROVED"|"VOID")=>{if(!doc)return;setBusy(true);setMessage("");try{await updateAdministrationDocumentStatus({id:doc.id,status,expectedUpdatedAt:new Date(doc.updatedAt).toISOString(),note:null});setMessage(`Status diubah menjadi ${status.replaceAll("_"," ")}.`);await q.refetch();}catch(e:any){setMessage(e?.message||"Status belum berhasil diubah.")}finally{setBusy(false)}};
 const vars:any=doc?.variableSnapshot||{};const transitions:Record<string,Array<any>>={DRAFT:[["Ajukan Review","IN_REVIEW"],["Batalkan Draft","VOID"]],IN_REVIEW:[["Kembalikan Revisi","RETURNED_FOR_REVISION"],["Setujui Internal","APPROVED"],["Batalkan","VOID"]],RETURNED_FOR_REVISION:[["Kembalikan ke Draft","DRAFT"],["Ajukan Review Lagi","IN_REVIEW"],["Batalkan","VOID"]],APPROVED:[["Void","VOID"]],VOID:[]};
 return <SchoolLayout user={user}><div className="space-y-5">{q.isLoading?<div className="flex min-h-[55vh] items-center justify-center"><M3CircularProgress size={38}/></div>:q.error||!doc?<M3Banner variant="error" supportingText={(q.error as any)?.message||"Draft tidak ditemukan."}/>:<><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="v2-eyebrow">TATA USAHA · DRAFT</p><h1 className="mt-1 text-2xl font-semibold">{doc.subject||doc.title}</h1><p className="mt-1 text-sm text-md-on-surface-variant">{doc.template.name} · versi template {doc.templateVersion.version} · revisi draft {doc.revision}</p></div><M3Badge variant={variant(doc.status)}>{doc.status.replaceAll("_"," ")}</M3Badge></header>
 <M3Banner variant="warning" headline="Belum merupakan surat resmi" supportingText="Nomor final dan tanda tangan resmi belum diaktifkan pada Mode Starter. Halaman ini digunakan untuk menyusun, mempreview, dan mereview kerangka surat."/>{message&&<M3Banner variant={message.startsWith("Status diubah")?"success":"warning"} supportingText={message} dismissible onDismiss={()=>setMessage("")}/>}<div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_320px]">
 <M3Card variant="outlined" className="overflow-hidden"><div className="border-b border-md-outline-variant px-4 py-3"><h2 className="text-sm font-semibold">Preview Dokumen</h2><p className="text-[11px] text-md-on-surface-variant">Preview A4 konseptual menggunakan snapshot saat draft dibuat.</p></div><div className="overflow-auto bg-md-surface-container p-3 sm:p-6"><article className="mx-auto min-h-[900px] max-w-[794px] bg-white px-[72px] py-[64px] text-[13px] leading-6 text-black shadow-sm"><header className="border-b-2 border-black pb-3 text-center"><p className="text-[16px] font-bold uppercase">{vars.school?.name||"SEKOLAH"}</p><p className="mt-1 text-[11px]">{[vars.school?.address,vars.school?.city,vars.school?.province].filter(Boolean).join(" · ")}</p><p className="text-[11px]">{[vars.school?.phone,vars.school?.email].filter(Boolean).join(" · ")}</p></header><div className="mt-6 grid grid-cols-[90px_1fr] gap-y-1"><span>Nomor</span><span>: DRAFT / BELUM DITERBITKAN</span><span>Perihal</span><span>: {doc.subject||doc.title}</span></div>{doc.recipientName&&<div className="mt-6"><p>Yth. {doc.recipientName}</p>{doc.recipientAddress&&<p>{doc.recipientAddress}</p>}</div>}<div className="mt-6 [&_table]:w-full [&_td]:align-top [&_td]:py-0.5" dangerouslySetInnerHTML={{__html:doc.renderedHtml}}/><div className="ml-auto mt-12 w-64 text-center"><p>{vars.document?.date||""}</p><p className="mt-1">Penandatangan belum dikonfigurasi</p><div className="h-20"/><p className="font-semibold">________________________</p></div></article></div></M3Card>
 <div className="space-y-4"><M3Card variant="outlined" className="p-4"><p className="text-xs font-semibold">Workflow Internal</p><div className="mt-3 grid gap-2">{(transitions[doc.status]||[]).map(([label,status]:any)=><M3Button key={status} variant={status==="VOID"?"outlined":status==="APPROVED"?"tonal":"filled"} onClick={()=>change(status)} isLoading={busy}>{label}</M3Button>)}{!(transitions[doc.status]||[]).length&&<p className="text-xs text-md-on-surface-variant">Tidak ada transisi lanjutan pada status ini.</p>}</div></M3Card><M3Card variant="filled" className="p-4"><p className="text-xs font-semibold">Metadata</p><dl className="mt-2 space-y-2 text-xs"><div><dt className="text-md-on-surface-variant">Dibuat</dt><dd className="font-medium">{fmt(doc.createdAt)}</dd></div><div><dt className="text-md-on-surface-variant">Pembuat</dt><dd className="font-medium">{doc.createdBy?.name||doc.createdBy?.email||"-"}</dd></div><div><dt className="text-md-on-surface-variant">Siswa terkait</dt><dd className="font-medium">{doc.relatedStudent?.name||"Tidak ada"}</dd></div></dl></M3Card><M3Card variant="outlined" className="overflow-hidden"><div className="border-b border-md-outline-variant px-4 py-3"><p className="text-xs font-semibold">Audit Trail</p></div><div className="divide-y divide-md-outline-variant/60">{doc.auditEvents.map((event:any)=><div key={event.id} className="px-4 py-3"><p className="text-[11.5px] font-medium">{event.summary}</p><p className="mt-0.5 text-[10.5px] text-md-on-surface-variant">{fmt(event.createdAt)} · {event.actor?.name||"System"}</p></div>)}</div></M3Card></div>
 </div></>}
 </div></SchoolLayout>
}
