import { type AuthUser } from "wasp/auth";
import { getAdministrationWorkspace, useQuery } from "wasp/client/operations";
import { SchoolLayout } from "../../school/components/SchoolLayout";
import { M3Badge, M3Banner, M3Button, M3Card, M3CircularProgress, M3EmptyState } from "../../client/components/m3";

function statusVariant(status:string){if(status==="APPROVED")return"success" as const;if(status==="IN_REVIEW")return"primary" as const;if(status==="VOID")return"error" as const;if(status==="RETURNED_FOR_REVISION")return"warning" as const;return"outline" as const;}
function date(value:any){return new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}
export function AdministrationOutgoingPage({user}:{user:AuthUser}){
 const q=useQuery(getAdministrationWorkspace);const data:any=q.data;
 return <SchoolLayout user={user}><div className="space-y-5"><header className="flex items-start justify-between gap-3"><div><p className="v2-eyebrow">TATA USAHA</p><h1 className="mt-1 text-2xl font-semibold">Surat Keluar</h1><p className="mt-1 text-sm text-md-on-surface-variant">Kelola draft dan alur review. Penerbitan nomor resmi masih dinonaktifkan pada mode starter.</p></div><M3Button href="/school/administration/outgoing/new" icon="add">Buat Draft</M3Button></header>
 {q.isLoading?<div className="flex min-h-[40vh] items-center justify-center"><M3CircularProgress size={36}/></div>:q.error?<M3Banner variant="error" supportingText={(q.error as any)?.message||"Data gagal dimuat."}/>:!data?.initialized?<M3EmptyState icon="description" title="Kerangka TU belum disiapkan" description="Buka Dashboard TU dan inisialisasi template starter terlebih dahulu." actionLabel="Buka Dashboard TU" actionHref="/school/administration"/>:<><M3Banner variant="warning" supportingText={data.starterMode.message}/><M3Card variant="outlined" className="overflow-hidden">{data.documents.length?<div className="divide-y divide-md-outline-variant/60">{data.documents.map((doc:any)=><a key={doc.id} href={`/school/administration/documents/${doc.id}`} className="grid gap-2 px-4 py-3.5 hover:bg-md-surface-container/55 sm:grid-cols-[minmax(0,1fr)_160px_140px] sm:items-center"><div className="min-w-0"><p className="truncate text-[13.5px] font-semibold">{doc.subject||doc.title}</p><p className="mt-0.5 truncate text-[11.5px] text-md-on-surface-variant">{doc.template.name} · {doc.recipientName||"Belum ada penerima"} · oleh {doc.createdBy?.name||doc.createdBy?.email||"-"}</p></div><M3Badge variant={statusVariant(doc.status)} size="sm">{doc.status.replaceAll("_"," ")}</M3Badge><span className="text-[11px] text-md-on-surface-variant sm:text-right">{date(doc.updatedAt)}</span></a>)}</div>:<div className="p-6"><M3EmptyState icon="outbox" title="Belum ada draft surat" description="Pilih template umum lalu buat draft pertama." actionLabel="Buat Draft Surat" actionHref="/school/administration/outgoing/new"/></div>}</M3Card></>}
 </div></SchoolLayout>
}
